spring:
  dataSource:
    username: root
    password: m123
    url: jdbc:mysql://127.0.0.1:3306/quartz?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&zeroDateTimeBehavior=convertToNull&useSSL=false